[package]
name = "asm_6502"
version = "0.1.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
cli = ["argparse"]

[dependencies]
lazy_static = "*"
argparse = {version = "0.2.2", optional = true}